class Autogenerated {
  int? reporttypeId;
  String? reporttypeName;
  int? servicetypeId;

  Autogenerated({this.reporttypeId, this.reporttypeName, this.servicetypeId});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    reporttypeId = json['reporttype_id'];
    reporttypeName = json['reporttype_name'];
    servicetypeId = json['servicetype_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['reporttype_id'] = this.reporttypeId;
    data['reporttype_name'] = this.reporttypeName;
    data['servicetype_id'] = this.servicetypeId;
    return data;
  }
}
