class Autogenerated {
  String? status;
  Data? data;

  Autogenerated({this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  String? version;
  String? releaseDate;
  int? isCurrent;

  Data({this.id, this.version, this.releaseDate, this.isCurrent});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    version = json['version'];
    releaseDate = json['release_date'];
    isCurrent = json['is_current'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['version'] = this.version;
    data['release_date'] = this.releaseDate;
    data['is_current'] = this.isCurrent;
    return data;
  }
}